// <auto-generated />
namespace eReg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Onappl_Add_date_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Onappl_Add_date_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201504090709312_Onappl_Add_date_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
